filter:
    paths: [app/*, config/*, database/*, routes/*, bootstrap/*]
    excluded_paths:
      - "app/Console/*"
before_commands:
    - 'composer install --dev --prefer-source'
    - 'cp .env.example .env'
    - 'php artisan jwt:secret -f'
tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests]
