preset: psr2
risky: true

enabled:
  - short_array_syntax
  - combine_consecutive_unsets
  - explicit_indirect_variable
  - method_separation
  - no_multiline_whitespace_before_semicolons
  - single_quote
  - length_ordered_imports
  - not_operator_with_successor_space
  - binary_operator_spaces
  - align_double_arrow
  - unalign_equals
  - blank_line_after_opening_tag
  - blank_line_before_return
  - combine_consecutive_issets
  - declare_equal_normalize
  - function_typehint_space
  - method_chaining_indentation
  - hash_to_slash_comment
  - include
  - lowercase_cast
  - no_blank_lines_after_class_opening
  - no_empty_statement
  - no_extra_consecutive_blank_lines
  - no_leading_import_slash
  - no_multiline_whitespace_around_double_arrow
  - no_trailing_comma_in_singleline_array
  - single_blank_line_before_namespace
  - ternary_operator_spaces
  - trailing_comma_in_multiline_array
  - trim_array_spaces
  - unary_operator_spaces
  - whitespace_after_comma_in_array
  - no_unused_imports
  - no_whitespace_before_comma_in_array
  - no_whitespace_in_blank_line
  - object_operator_without_whitespace

finder:
  exclude:
    - modules
    - node_modules
    - storage
    - vendor
    - run
  name: "*.php"
  not-name: "*.blade.php"