language: php

php:
  - "7.2"
  - "7.3"
  - "7.4"

git:
  depth: 1

services:
  - redis-server

before_script:
  - composer self-update
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  - cp .env.example .env
  - php artisan jwt:secret -f

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml

matrix:
  fast_finish: true
