language: php

php:
  # - 7.0
  - 7.1
  - 7.2
  - 7.3

git:
  depth: 1

services:
  - redis-server

before_install:
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

script:
  - vendor/bin/phpunit
