version: "3"
services:
  app:
    image: duccnzj/app
    volumes:
      - /Users/congcong/Lumen/lumen-app:/var/www/html
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./default.conf:/etc/nginx/sites-available/default
    ports:
      - 8001:80
    networks:
      - appnet
    depends_on:
      - db
      - redis
    environment:
      BASH_NAMES: migrate.sh
  redis:
    image: redis:alpine
    networks:
      - appnet
    ports:
      - 6379:6379
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    networks:
      - appnet
    ports:
      - 3305:3306
    volumes:
      - dbdata:/var/lib/mysql
  web:
    image: nginx
    volumes:
     - ./mysite.template:/etc/nginx/conf.d/mysite.template
     - /Users/congcong/Vue/blog/dist:/usr/share/nginx/html/front
     - /Users/congcong/Vue/blog-admin/dist:/usr/share/nginx/html/background
    ports:
     - "8003:8009"
     - "8002:8010"
    environment:
     # - NGINX_HOST=foobar.com
     - FRONT_PORT=8009
     - BACK_PORT=8010
    networks:
      - appnet
    # command: /bin/bash -c "exec nginx -g 'daemon off;'"
    command: /bin/bash -c "envsubst '$$FRONT_PORT $$BACK_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
networks:
  appnet:
    driver: bridge
volumes:
  appdata:
    driver: local
  webdata:
    driver: local
  dbdata:
    driver: local

