version: "3"
services:
  elasticsearch:
    image: registry.cn-hangzhou.aliyuncs.com/duc-cnzj/elasticsearch_with_ik:6.4.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - appnet
  app:
    image: registry.cn-hangzhou.aliyuncs.com/duc-cnzj/app:latest
    working_dir: /var/www/html
    volumes:
      - ../.:/var/www/html
      - ./default.conf:/etc/nginx/sites-available/default
    ports:
      - 8001:80
    networks:
      - appnet
    depends_on:
      - elasticsearch
      - redis
      - db
      - web
    environment:
      BASH_NAMES: ./shell/init.sh,./shell/migrate.sh,./shell/test.sh
  redis:
    image: redis:alpine
    networks:
      - appnet
    ports:
      - 16379:6379
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    networks:
      - appnet
    ports:
      - 13306:3306
    volumes:
      - dbdata:/var/lib/mysql
  web:
    image: nginx
    volumes:
     - ./mysite.template:/etc/nginx/conf.d/mysite.template
     - ./front:/usr/share/nginx/html/front
     - ./back:/usr/share/nginx/html/background
    ports:
     - ${FRONT_PORT:-8003}:8009
     - ${BACK_PORT:-8002}:8010
    environment:
     - FRONT_PORT=8009
     - BACK_PORT=8010
    networks:
      - appnet
    command: /bin/bash -c "envsubst '$$FRONT_PORT $$BACK_PORT' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
networks:
  appnet:
    driver: bridge
volumes:
  appdata:
    driver: local
  webdata:
    driver: local
  dbdata:
    driver: local
  esdata:
    driver: local

